// <auto-generated />
using System;
using DotaNerf.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotaNerf.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotaNerf.Models.GameStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Assists")
                        .HasColumnType("int");

                    b.Property<int?>("Deaths")
                        .HasColumnType("int");

                    b.Property<int?>("GameDuration")
                        .HasColumnType("int");

                    b.Property<int>("GameResult")
                        .HasColumnType("int");

                    b.Property<double?>("Gpm")
                        .HasColumnType("float");

                    b.Property<string>("HeroPlayed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Kills")
                        .HasColumnType("int");

                    b.Property<int?>("LastHits")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Xpm")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("GameStats");
                });

            modelBuilder.Entity("DotaNerf.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GamesLost")
                        .HasColumnType("int");

                    b.Property<int>("GamesWon")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalGames")
                        .HasColumnType("int");

                    b.Property<double>("Winrate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1e29d5e-1c4b-4b8a-9b1e-1c4b4b8a9b1e"),
                            GamesLost = 3,
                            GamesWon = 6,
                            Name = "dummy",
                            TotalGames = 9,
                            Winrate = 67.0
                        },
                        new
                        {
                            Id = new Guid("b2f29d5e-2d4b-4c8a-9c2e-2d4b5c8a9c2e"),
                            GamesLost = 3,
                            GamesWon = 6,
                            Name = "Stoqn (kolega)",
                            TotalGames = 9,
                            Winrate = 67.0
                        },
                        new
                        {
                            Id = new Guid("c3f39d5e-3e4b-4c8a-9d3e-3e4b6c8a9d3e"),
                            GamesLost = 7,
                            GamesWon = 12,
                            Name = "Veni",
                            TotalGames = 19,
                            Winrate = 63.0
                        },
                        new
                        {
                            Id = new Guid("d4f49d5e-4f4b-4c8a-9e4e-4f4b7c8a9e4e"),
                            GamesLost = 6,
                            GamesWon = 9,
                            Name = "Kriskata",
                            TotalGames = 15,
                            Winrate = 60.0
                        },
                        new
                        {
                            Id = new Guid("e5f59d5e-5f4b-4c8a-9f5e-5f4b8c8a9f5e"),
                            GamesLost = 7,
                            GamesWon = 10,
                            Name = "Marto",
                            TotalGames = 17,
                            Winrate = 59.0
                        },
                        new
                        {
                            Id = new Guid("f6f69d5e-6f4b-4c8a-9f6e-6f4b9c8a9f6e"),
                            GamesLost = 7,
                            GamesWon = 7,
                            Name = "Steli",
                            TotalGames = 14,
                            Winrate = 50.0
                        },
                        new
                        {
                            Id = new Guid("07f79d5e-7f4b-4c8a-9f7e-7f4b0c8a9f7e"),
                            GamesLost = 9,
                            GamesWon = 10,
                            Name = "Rumen",
                            TotalGames = 19,
                            Winrate = 52.0
                        },
                        new
                        {
                            Id = new Guid("18f89d5e-8f4b-4c8a-9f8e-8f4b1c8a9f8e"),
                            GamesLost = 9,
                            GamesWon = 6,
                            Name = "Bobur Kurva",
                            TotalGames = 15,
                            Winrate = 40.0
                        },
                        new
                        {
                            Id = new Guid("29f99d5e-9f4b-4c8a-9f9e-9f4b2c8a9f9e"),
                            GamesLost = 10,
                            GamesWon = 6,
                            Name = "Dj Misho",
                            TotalGames = 16,
                            Winrate = 38.0
                        },
                        new
                        {
                            Id = new Guid("30f09d5e-0f4b-4c8a-9f0e-0f4b3c8a9f0e"),
                            GamesLost = 12,
                            GamesWon = 7,
                            Name = "Kuncho",
                            TotalGames = 19,
                            Winrate = 37.0
                        },
                        new
                        {
                            Id = new Guid("41f19d5e-1f4b-4c8a-9f1e-1f4b4c8a9f1e"),
                            GamesLost = 4,
                            GamesWon = 1,
                            Name = "Sofiqneca",
                            TotalGames = 5,
                            Winrate = 20.0
                        },
                        new
                        {
                            Id = new Guid("52f29d5e-2f4b-4c8a-9f2e-2f4b5c8a9f2e"),
                            GamesLost = 6,
                            GamesWon = 2,
                            Name = "Vaneto",
                            TotalGames = 8,
                            Winrate = 25.0
                        },
                        new
                        {
                            Id = new Guid("63f39d5e-3f4b-4c8a-9f3e-3f4b6c8a9f3e"),
                            GamesLost = 6,
                            GamesWon = 0,
                            Name = "Mario",
                            TotalGames = 6,
                            Winrate = 0.0
                        });
                });

            modelBuilder.Entity("DotaNerf.Models.GameStats", b =>
                {
                    b.HasOne("DotaNerf.Models.Player", "Player")
                        .WithMany("Games")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DotaNerf.Models.Player", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
